# Generated by Django 3.1.3 on 2020-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_croppie', '0003_auto_20201126_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
